# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semantic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'semantic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esemantic.proto\x12\x06semcom\"\x88\x01\n\x07\x43ommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x06params\x18\x02 \x03(\x0b\x32\x1b.semcom.Command.ParamsEntry\x12\x13\n\x0b\x64\x65\x61\x64line_ms\x18\x03 \x01(\x04\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x86\x01\n\x06Status\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\x0e\n\x06health\x18\x02 \x01(\r\x12,\n\x07metrics\x18\x03 \x03(\x0b\x32\x1b.semcom.Status.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x05\x41lert\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\'\n\x03\x41\x63k\x12\x12\n\nref_msg_id\x18\x01 \x01(\x04\x12\x0c\n\x04note\x18\x02 \x01(\t\"K\n\x08\x45nvelope\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x1d\n\x04type\x18\x02 \x01(\x0e\x32\x0f.semcom.SemType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c*W\n\x07SemType\x12\x0f\n\x0bSEM_UNKNOWN\x10\x00\x12\x0f\n\x0bSEM_COMMAND\x10\x01\x12\x0e\n\nSEM_STATUS\x10\x02\x12\r\n\tSEM_ALERT\x10\x03\x12\x0b\n\x07SEM_ACK\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semantic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_PARAMSENTRY']._loaded_options = None
  _globals['_COMMAND_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_STATUS_METRICSENTRY']._loaded_options = None
  _globals['_STATUS_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_SEMTYPE']._serialized_start=476
  _globals['_SEMTYPE']._serialized_end=563
  _globals['_COMMAND']._serialized_start=27
  _globals['_COMMAND']._serialized_end=163
  _globals['_COMMAND_PARAMSENTRY']._serialized_start=118
  _globals['_COMMAND_PARAMSENTRY']._serialized_end=163
  _globals['_STATUS']._serialized_start=166
  _globals['_STATUS']._serialized_end=300
  _globals['_STATUS_METRICSENTRY']._serialized_start=254
  _globals['_STATUS_METRICSENTRY']._serialized_end=300
  _globals['_ALERT']._serialized_start=302
  _globals['_ALERT']._serialized_end=356
  _globals['_ACK']._serialized_start=358
  _globals['_ACK']._serialized_end=397
  _globals['_ENVELOPE']._serialized_start=399
  _globals['_ENVELOPE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
