name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate protobuf
      run: |
        python -m grpc_tools.protoc -I proto --python_out=. proto/semantic.proto

    - name: Lint
      run: flake8 .

    - name: Type check
      run: mypy --ignore-missing-imports .

    - name: Unit tests
      run: pytest -q

    - name: Docker build (sanity)
      run: docker build -t semcomms:ci .

